version: '3.1'

services:
  mtb:
    depends_on:
      - mtb-db
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DB_USERNAME=${BOT_DB_USERNAME}
      - BOT_DB_PASSWORD=${BOT_DB_PASSWORD}
    restart: always
  mtb-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'mtb_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${BOT_DB_USERNAME}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      # Password for root access
      #      MYSQL_ROOT_PASSWORD: 'root'
      #      MYSQL_USER: ${BOT_DB_USERNAME}
      #      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}

      #      MYSQL_DATABASE: 'mtb_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3307'
#    command: --character-set-server=utf8 --collation-server=utf8_general_cimmand: --character-set-server=utf8 --collation-server=utf8_general_ci