version: '3.1'

services:
  mtb:
    depends_on:
      - mtb-db
    build:
      context: .
    environment:
       BOT_NAME: ${BOT_NAME}
       BOT_TOKEN: ${BOT_TOKEN}
       BOT_DB_USERNAME: ${BOT_DB_USERNAME}
       BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always

  mtb-db:
      image: mysql:8.0.30-debian
      restart: always
      environment:
#        MYSQL_USER: ${BOT_DB_USERNAME}
#        MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
        MYSQL_USER: 'dev_mtb_db_user'
        MYSQL_PASSWORD: 'dev_mtb_db_password'
        MYSQL_DATABASE: 'dev_mtb_db'
        MYSQL_ROOT_PASSWORD: 'Spencer86'
      ports:
        - "306:3306"
      expose:
        - "3306"

#services:
#  jrtb-bot:
#    depends_on:
#      - jrtb-db
#    build:
#      context: .
#    environment:
#      BOT_NAME: ${BOT_NAME}
#      BOT_TOKEN: ${BOT_TOKEN}
#      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
#      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
#    restart: always
#  jrtb-db:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_USER: ${BOT_DB_USERNAME}
#      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
#      MYSQL_DATABASE: 'jrtb_db'
#      MYSQL_ROOT_PASSWORD: 'root'
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    command: --character-set-server=utf8 --collation-server=utf8_general_ci